/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowauthfac (void)
{
  GtkWidget *windowauthfac;
  GtkWidget *fixed1;
  GtkWidget *entryuserfac;
  GtkWidget *entrypassfac;
  GtkWidget *erreurauth;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *buttonlogfac;

  windowauthfac = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowauthfac), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowauthfac), fixed1);

  entryuserfac = gtk_entry_new ();
  gtk_widget_show (entryuserfac);
  gtk_fixed_put (GTK_FIXED (fixed1), entryuserfac, 128, 32);
  gtk_widget_set_size_request (entryuserfac, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuserfac), 8226);

  entrypassfac = gtk_entry_new ();
  gtk_widget_show (entrypassfac);
  gtk_fixed_put (GTK_FIXED (fixed1), entrypassfac, 128, 80);
  gtk_widget_set_size_request (entrypassfac, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypassfac), 8226);

  erreurauth = gtk_text_view_new ();
  gtk_widget_show (erreurauth);
  gtk_fixed_put (GTK_FIXED (fixed1), erreurauth, 120, 160);
  gtk_widget_set_size_request (erreurauth, 122, 18);

  label2 = gtk_label_new (_("password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 80);
  gtk_widget_set_size_request (label2, 88, 17);

  label1 = gtk_label_new (_("username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 40);
  gtk_widget_set_size_request (label1, 80, 16);

  buttonlogfac = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (buttonlogfac);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonlogfac, 288, 232);
  gtk_widget_set_size_request (buttonlogfac, 66, 29);

  g_signal_connect ((gpointer) buttonlogfac, "clicked",
                    G_CALLBACK (on_buttonlogfac_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowauthfac, windowauthfac, "windowauthfac");
  GLADE_HOOKUP_OBJECT (windowauthfac, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowauthfac, entryuserfac, "entryuserfac");
  GLADE_HOOKUP_OBJECT (windowauthfac, entrypassfac, "entrypassfac");
  GLADE_HOOKUP_OBJECT (windowauthfac, erreurauth, "erreurauth");
  GLADE_HOOKUP_OBJECT (windowauthfac, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowauthfac, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowauthfac, buttonlogfac, "buttonlogfac");

  return windowauthfac;
}

GtkWidget*
create_windowespfac (void)
{
  GtkWidget *windowespfac;
  GtkWidget *notebook1;
  GtkWidget *notebook2;
  GtkWidget *fixed3;
  GtkWidget *treeviewfacturation;
  GtkWidget *buttonrefrefac;
  GtkWidget *image1;
  GtkWidget *client_payement;
  GtkWidget *image6;
  GtkWidget *buttonquitterfacture;
  GtkWidget *image7;
  GtkWidget *label5;
  GtkWidget *fixed2;
  GtkWidget *entryidaj;
  GtkWidget *entryNfac;
  GtkWidget *entryagentfac;
  GtkObject *spinbuttonaj_dt_fac_adj;
  GtkWidget *spinbuttonaj_dt_fac;
  GtkObject *spinbuttonaj_fac_mois_adj;
  GtkWidget *spinbuttonaj_fac_mois;
  GtkObject *spinbutton_aj_an_fac_adj;
  GtkWidget *spinbutton_aj_an_fac;
  GtkWidget *entryIdprestationfact;
  GtkWidget *entrycodecoupan;
  GtkWidget *entryMantantHT;
  GtkWidget *entryMantantTTC;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *comboboxAjfac;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *label17;
  GtkWidget *buttonajfac;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *fixed4;
  GtkWidget *entryIDsupfac;
  GtkWidget *label18;
  GtkWidget *buttonsuppfac;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image3;
  GtkWidget *label19;
  GtkWidget *label7;
  GtkWidget *fixed5;
  GtkWidget *entryidmodif;
  GtkWidget *entrymntmod;
  GtkWidget *entryNtmodif;
  GtkWidget *entryemisparmodif;
  GtkWidget *entryprestationmodif;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label20;
  GtkWidget *entrydatemodif;
  GtkWidget *label45;
  GtkWidget *buttonrecherchefacture;
  GtkWidget *buttonmodifier1facture;
  GtkWidget *label8;
  GtkWidget *label3;

  windowespfac = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (windowespfac), 1);
  gtk_window_set_title (GTK_WINDOW (windowespfac), _("espace facturation"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (windowespfac), notebook1);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed3);

  treeviewfacturation = gtk_tree_view_new ();
  gtk_widget_show (treeviewfacturation);
  gtk_fixed_put (GTK_FIXED (fixed3), treeviewfacturation, 32, 48);
  gtk_widget_set_size_request (treeviewfacturation, 912, 336);

  buttonrefrefac = gtk_button_new ();
  gtk_widget_show (buttonrefrefac);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonrefrefac, 344, 432);
  gtk_widget_set_size_request (buttonrefrefac, 66, 29);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (buttonrefrefac), image1);

  client_payement = gtk_button_new ();
  gtk_widget_show (client_payement);
  gtk_fixed_put (GTK_FIXED (fixed3), client_payement, 896, 8);
  gtk_widget_set_size_request (client_payement, 136, 32);

  image6 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (client_payement), image6);

  buttonquitterfacture = gtk_button_new ();
  gtk_widget_show (buttonquitterfacture);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonquitterfacture, 792, 8);
  gtk_widget_set_size_request (buttonquitterfacture, 66, 29);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (buttonquitterfacture), image7);

  label5 = gtk_label_new (_("afficher"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label5);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed2);

  entryidaj = gtk_entry_new ();
  gtk_widget_show (entryidaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidaj, 368, 8);
  gtk_widget_set_size_request (entryidaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidaj), 8226);

  entryNfac = gtk_entry_new ();
  gtk_widget_show (entryNfac);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNfac, 368, 48);
  gtk_widget_set_size_request (entryNfac, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNfac), 8226);

  entryagentfac = gtk_entry_new ();
  gtk_widget_show (entryagentfac);
  gtk_fixed_put (GTK_FIXED (fixed2), entryagentfac, 368, 88);
  gtk_widget_set_size_request (entryagentfac, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryagentfac), 8226);

  spinbuttonaj_dt_fac_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonaj_dt_fac = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonaj_dt_fac_adj), 1, 0);
  gtk_widget_show (spinbuttonaj_dt_fac);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonaj_dt_fac, 384, 128);
  gtk_widget_set_size_request (spinbuttonaj_dt_fac, 60, 27);

  spinbuttonaj_fac_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonaj_fac_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonaj_fac_mois_adj), 1, 0);
  gtk_widget_show (spinbuttonaj_fac_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonaj_fac_mois, 464, 128);
  gtk_widget_set_size_request (spinbuttonaj_fac_mois, 60, 27);

  spinbutton_aj_an_fac_adj = gtk_adjustment_new (1, 2000, 2050, 1, 10, 10);
  spinbutton_aj_an_fac = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_an_fac_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_an_fac);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_aj_an_fac, 536, 128);
  gtk_widget_set_size_request (spinbutton_aj_an_fac, 60, 27);

  entryIdprestationfact = gtk_entry_new ();
  gtk_widget_show (entryIdprestationfact);
  gtk_fixed_put (GTK_FIXED (fixed2), entryIdprestationfact, 368, 224);
  gtk_widget_set_size_request (entryIdprestationfact, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIdprestationfact), 8226);

  entrycodecoupan = gtk_entry_new ();
  gtk_widget_show (entrycodecoupan);
  gtk_fixed_put (GTK_FIXED (fixed2), entrycodecoupan, 368, 328);
  gtk_widget_set_size_request (entrycodecoupan, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodecoupan), 8226);

  entryMantantHT = gtk_entry_new ();
  gtk_widget_show (entryMantantHT);
  gtk_fixed_put (GTK_FIXED (fixed2), entryMantantHT, 368, 280);
  gtk_widget_set_size_request (entryMantantHT, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMantantHT), 8226);

  entryMantantTTC = gtk_entry_new ();
  gtk_widget_show (entryMantantTTC);
  gtk_fixed_put (GTK_FIXED (fixed2), entryMantantTTC, 376, 384);
  gtk_widget_set_size_request (entryMantantTTC, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMantantTTC), 8226);

  label9 = gtk_label_new (_("ID"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 256, 16);
  gtk_widget_set_size_request (label9, 41, 17);

  label10 = gtk_label_new (_("N"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 248, 56);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("Emis par "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 248, 96);
  gtk_widget_set_size_request (label11, 72, 17);

  label12 = gtk_label_new (_("date"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 256, 144);
  gtk_widget_set_size_request (label12, 49, 17);

  label13 = gtk_label_new (_("prestation"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 248, 184);
  gtk_widget_set_size_request (label13, 96, 16);

  label14 = gtk_label_new (_("ID prestation "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 248, 240);
  gtk_widget_set_size_request (label14, 96, 16);

  comboboxAjfac = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxAjfac);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxAjfac, 368, 176);
  gtk_widget_set_size_request (comboboxAjfac, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAjfac), _("vol "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAjfac), _("hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAjfac), _("hotel"));

  label16 = gtk_label_new (_("montantHT"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 248, 288);
  gtk_widget_set_size_request (label16, 80, 16);

  label15 = gtk_label_new (_("code coupan "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 240, 336);
  gtk_widget_set_size_request (label15, 104, 16);

  label17 = gtk_label_new (_("montantTTC"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 232, 392);
  gtk_widget_set_size_request (label17, 104, 16);

  buttonajfac = gtk_button_new ();
  gtk_widget_show (buttonajfac);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonajfac, 872, 400);
  gtk_widget_set_size_request (buttonajfac, 66, 29);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (buttonajfac), image2);

  label6 = gtk_label_new (_("ajouter"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label6);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed4);

  entryIDsupfac = gtk_entry_new ();
  gtk_widget_show (entryIDsupfac);
  gtk_fixed_put (GTK_FIXED (fixed4), entryIDsupfac, 216, 48);
  gtk_widget_set_size_request (entryIDsupfac, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDsupfac), 8226);

  label18 = gtk_label_new (_("ID"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 128, 56);
  gtk_widget_set_size_request (label18, 49, 17);

  buttonsuppfac = gtk_button_new ();
  gtk_widget_show (buttonsuppfac);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsuppfac, 896, 400);
  gtk_widget_set_size_request (buttonsuppfac, 66, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonsuppfac), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox1), image3, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox1), label19, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("supprimer"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label7);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed5);

  entryidmodif = gtk_entry_new ();
  gtk_widget_show (entryidmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), entryidmodif, 336, 40);
  gtk_widget_set_size_request (entryidmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidmodif), 8226);

  entrymntmod = gtk_entry_new ();
  gtk_widget_show (entrymntmod);
  gtk_fixed_put (GTK_FIXED (fixed5), entrymntmod, 336, 304);
  gtk_widget_set_size_request (entrymntmod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymntmod), 8226);

  entryNtmodif = gtk_entry_new ();
  gtk_widget_show (entryNtmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), entryNtmodif, 336, 96);
  gtk_widget_set_size_request (entryNtmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNtmodif), 8226);

  entryemisparmodif = gtk_entry_new ();
  gtk_widget_show (entryemisparmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), entryemisparmodif, 336, 144);
  gtk_widget_set_size_request (entryemisparmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemisparmodif), 8226);

  entryprestationmodif = gtk_entry_new ();
  gtk_widget_show (entryprestationmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), entryprestationmodif, 336, 248);
  gtk_widget_set_size_request (entryprestationmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprestationmodif), 8226);

  label41 = gtk_label_new (_("N"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed5), label41, 224, 96);
  gtk_widget_set_size_request (label41, 49, 17);

  label42 = gtk_label_new (_("Emis par"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed5), label42, 224, 153);
  gtk_widget_set_size_request (label42, 72, 16);

  label43 = gtk_label_new (_("date"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 208, 208);
  gtk_widget_set_size_request (label43, 73, 16);

  label44 = gtk_label_new (_("prestation"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 184, 248);
  gtk_widget_set_size_request (label44, 97, 16);

  label20 = gtk_label_new (_("ID"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 208, 48);
  gtk_widget_set_size_request (label20, 57, 16);

  entrydatemodif = gtk_entry_new ();
  gtk_widget_show (entrydatemodif);
  gtk_fixed_put (GTK_FIXED (fixed5), entrydatemodif, 336, 200);
  gtk_widget_set_size_request (entrydatemodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydatemodif), 8226);

  label45 = gtk_label_new (_("montant "));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed5), label45, 184, 304);
  gtk_widget_set_size_request (label45, 97, 17);

  buttonrecherchefacture = gtk_button_new_with_mnemonic (_("recherche"));
  gtk_widget_show (buttonrecherchefacture);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonrecherchefacture, 600, 32);
  gtk_widget_set_size_request (buttonrecherchefacture, 96, 21);

  buttonmodifier1facture = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (buttonmodifier1facture);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonmodifier1facture, 592, 360);
  gtk_widget_set_size_request (buttonmodifier1facture, 104, 29);

  label8 = gtk_label_new (_("modifier"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label8);

  label3 = gtk_label_new (_("agent"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);

  g_signal_connect ((gpointer) buttonrefrefac, "clicked",
                    G_CALLBACK (on_buttonrefrefac_clicked),
                    NULL);
  g_signal_connect ((gpointer) client_payement, "clicked",
                    G_CALLBACK (on_client_payement_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonquitterfacture, "clicked",
                    G_CALLBACK (on_buttonquitterfacture_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajfac, "clicked",
                    G_CALLBACK (on_buttonajfac_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuppfac, "clicked",
                    G_CALLBACK (on_buttonsuppfac_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrecherchefacture, "clicked",
                    G_CALLBACK (on_buttonrecherchefacture_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier1facture, "clicked",
                    G_CALLBACK (on_buttonmodifier1facture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowespfac, windowespfac, "windowespfac");
  GLADE_HOOKUP_OBJECT (windowespfac, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowespfac, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (windowespfac, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowespfac, treeviewfacturation, "treeviewfacturation");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonrefrefac, "buttonrefrefac");
  GLADE_HOOKUP_OBJECT (windowespfac, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowespfac, client_payement, "client_payement");
  GLADE_HOOKUP_OBJECT (windowespfac, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonquitterfacture, "buttonquitterfacture");
  GLADE_HOOKUP_OBJECT (windowespfac, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowespfac, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowespfac, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowespfac, entryidaj, "entryidaj");
  GLADE_HOOKUP_OBJECT (windowespfac, entryNfac, "entryNfac");
  GLADE_HOOKUP_OBJECT (windowespfac, entryagentfac, "entryagentfac");
  GLADE_HOOKUP_OBJECT (windowespfac, spinbuttonaj_dt_fac, "spinbuttonaj_dt_fac");
  GLADE_HOOKUP_OBJECT (windowespfac, spinbuttonaj_fac_mois, "spinbuttonaj_fac_mois");
  GLADE_HOOKUP_OBJECT (windowespfac, spinbutton_aj_an_fac, "spinbutton_aj_an_fac");
  GLADE_HOOKUP_OBJECT (windowespfac, entryIdprestationfact, "entryIdprestationfact");
  GLADE_HOOKUP_OBJECT (windowespfac, entrycodecoupan, "entrycodecoupan");
  GLADE_HOOKUP_OBJECT (windowespfac, entryMantantHT, "entryMantantHT");
  GLADE_HOOKUP_OBJECT (windowespfac, entryMantantTTC, "entryMantantTTC");
  GLADE_HOOKUP_OBJECT (windowespfac, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowespfac, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowespfac, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowespfac, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowespfac, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowespfac, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowespfac, comboboxAjfac, "comboboxAjfac");
  GLADE_HOOKUP_OBJECT (windowespfac, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowespfac, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowespfac, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonajfac, "buttonajfac");
  GLADE_HOOKUP_OBJECT (windowespfac, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowespfac, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowespfac, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowespfac, entryIDsupfac, "entryIDsupfac");
  GLADE_HOOKUP_OBJECT (windowespfac, label18, "label18");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonsuppfac, "buttonsuppfac");
  GLADE_HOOKUP_OBJECT (windowespfac, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowespfac, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowespfac, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowespfac, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowespfac, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowespfac, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowespfac, entryidmodif, "entryidmodif");
  GLADE_HOOKUP_OBJECT (windowespfac, entrymntmod, "entrymntmod");
  GLADE_HOOKUP_OBJECT (windowespfac, entryNtmodif, "entryNtmodif");
  GLADE_HOOKUP_OBJECT (windowespfac, entryemisparmodif, "entryemisparmodif");
  GLADE_HOOKUP_OBJECT (windowespfac, entryprestationmodif, "entryprestationmodif");
  GLADE_HOOKUP_OBJECT (windowespfac, label41, "label41");
  GLADE_HOOKUP_OBJECT (windowespfac, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowespfac, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowespfac, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowespfac, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowespfac, entrydatemodif, "entrydatemodif");
  GLADE_HOOKUP_OBJECT (windowespfac, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonrecherchefacture, "buttonrecherchefacture");
  GLADE_HOOKUP_OBJECT (windowespfac, buttonmodifier1facture, "buttonmodifier1facture");
  GLADE_HOOKUP_OBJECT (windowespfac, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowespfac, label3, "label3");

  return windowespfac;
}

GtkWidget*
create_windowesppayement (void)
{
  GtkWidget *windowesppayement;
  GtkWidget *notebook3;
  GtkWidget *fixed7;
  GtkWidget *entryIDpayement;
  GtkWidget *entrynomclientayement;
  GtkWidget *entryprenomclientpayement;
  GtkWidget *label39;
  GtkWidget *entrynumerocarte;
  GtkWidget *entrycodecarte;
  GtkWidget *label40;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *comboboxpayer;
  GtkWidget *label38;
  GtkWidget *buttonpaye;
  GtkWidget *payer;
  GtkWidget *fixed6;
  GtkWidget *treeviewclientpayement;
  GtkWidget *affichermesfacture;
  GtkWidget *image5;
  GtkWidget *label34;

  windowesppayement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowesppayement), _("payement client"));

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (windowesppayement), notebook3);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed7);

  entryIDpayement = gtk_entry_new ();
  gtk_widget_show (entryIDpayement);
  gtk_fixed_put (GTK_FIXED (fixed7), entryIDpayement, 104, 16);
  gtk_widget_set_size_request (entryIDpayement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDpayement), 8226);

  entrynomclientayement = gtk_entry_new ();
  gtk_widget_show (entrynomclientayement);
  gtk_fixed_put (GTK_FIXED (fixed7), entrynomclientayement, 104, 56);
  gtk_widget_set_size_request (entrynomclientayement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomclientayement), 8226);

  entryprenomclientpayement = gtk_entry_new ();
  gtk_widget_show (entryprenomclientpayement);
  gtk_fixed_put (GTK_FIXED (fixed7), entryprenomclientpayement, 104, 96);
  gtk_widget_set_size_request (entryprenomclientpayement, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomclientpayement), 8226);

  label39 = gtk_label_new (_("numero carte"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 40, 201);
  gtk_widget_set_size_request (label39, 112, 16);

  entrynumerocarte = gtk_entry_new ();
  gtk_widget_show (entrynumerocarte);
  gtk_fixed_put (GTK_FIXED (fixed7), entrynumerocarte, 176, 192);
  gtk_widget_set_size_request (entrynumerocarte, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumerocarte), 8226);

  entrycodecarte = gtk_entry_new ();
  gtk_widget_show (entrycodecarte);
  gtk_fixed_put (GTK_FIXED (fixed7), entrycodecarte, 176, 224);
  gtk_widget_set_size_request (entrycodecarte, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrycodecarte), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycodecarte), 8226);

  label40 = gtk_label_new (_("code"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 56, 232);
  gtk_widget_set_size_request (label40, 49, 17);

  label35 = gtk_label_new (_("ID"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 24, 24);
  gtk_widget_set_size_request (label35, 80, 16);

  label36 = gtk_label_new (_("nom"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 32, 64);
  gtk_widget_set_size_request (label36, 49, 16);

  label37 = gtk_label_new (_("prenom"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 32, 104);
  gtk_widget_set_size_request (label37, 73, 17);

  comboboxpayer = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxpayer);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxpayer, 168, 136);
  gtk_widget_set_size_request (comboboxpayer, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxpayer), _("visa "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxpayer), _("mastercard"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxpayer), _("paypall"));

  label38 = gtk_label_new (_("mode"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed7), label38, 64, 144);
  gtk_widget_set_size_request (label38, 49, 17);

  buttonpaye = gtk_button_new_with_mnemonic (_("payer"));
  gtk_widget_show (buttonpaye);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonpaye, 408, 248);
  gtk_widget_set_size_request (buttonpaye, 66, 29);

  payer = gtk_label_new (_("payer"));
  gtk_widget_show (payer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), payer);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed6);

  treeviewclientpayement = gtk_tree_view_new ();
  gtk_widget_show (treeviewclientpayement);
  gtk_fixed_put (GTK_FIXED (fixed6), treeviewclientpayement, 8, 32);
  gtk_widget_set_size_request (treeviewclientpayement, 496, 192);

  affichermesfacture = gtk_button_new ();
  gtk_widget_show (affichermesfacture);
  gtk_fixed_put (GTK_FIXED (fixed6), affichermesfacture, 416, 248);
  gtk_widget_set_size_request (affichermesfacture, 96, 29);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (affichermesfacture), image5);

  label34 = gtk_label_new (_("afficher"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label34);

  g_signal_connect ((gpointer) buttonpaye, "clicked",
                    G_CALLBACK (on_buttonpaye_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowesppayement, windowesppayement, "windowesppayement");
  GLADE_HOOKUP_OBJECT (windowesppayement, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (windowesppayement, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowesppayement, entryIDpayement, "entryIDpayement");
  GLADE_HOOKUP_OBJECT (windowesppayement, entrynomclientayement, "entrynomclientayement");
  GLADE_HOOKUP_OBJECT (windowesppayement, entryprenomclientpayement, "entryprenomclientpayement");
  GLADE_HOOKUP_OBJECT (windowesppayement, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowesppayement, entrynumerocarte, "entrynumerocarte");
  GLADE_HOOKUP_OBJECT (windowesppayement, entrycodecarte, "entrycodecarte");
  GLADE_HOOKUP_OBJECT (windowesppayement, label40, "label40");
  GLADE_HOOKUP_OBJECT (windowesppayement, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowesppayement, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowesppayement, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowesppayement, comboboxpayer, "comboboxpayer");
  GLADE_HOOKUP_OBJECT (windowesppayement, label38, "label38");
  GLADE_HOOKUP_OBJECT (windowesppayement, buttonpaye, "buttonpaye");
  GLADE_HOOKUP_OBJECT (windowesppayement, payer, "payer");
  GLADE_HOOKUP_OBJECT (windowesppayement, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowesppayement, treeviewclientpayement, "treeviewclientpayement");
  GLADE_HOOKUP_OBJECT (windowesppayement, affichermesfacture, "affichermesfacture");
  GLADE_HOOKUP_OBJECT (windowesppayement, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowesppayement, label34, "label34");

  return windowesppayement;
}

