/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAccueil (void);
GtkWidget* create_windowAuthenti (void);
GtkWidget* create_windowPrestataire (void);
GtkWidget* create_windowPrestEtOffre (void);
GtkWidget* create_windowCatamogue (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_window8 (void);
