/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAccueil (void);
GtkWidget* create_windowAuthenti (void);
GtkWidget* create_windowPrestataire (void);
GtkWidget* create_windowPrestEtOffre (void);
GtkWidget* create_windowCatamogue (void);
