/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_window1 (void);
GtkWidget* create_Sup (void);
GtkWidget* create_Modifie (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
