/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{

GtkWidget *windowAccueil;
GtkWidget *image1;
GtkWidget *image2;
GtkWidget *image3;
GtkWidget *image4;

GtkWidget *table1;
GtkWidget *table2;
GtkWidget *table3;
GtkWidget *table4;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

	table1=gtk_table_new(0,0,TRUE);
	gtk_container_add(GTK_CONTAINER(windowAccueil),GTK_WIDGET(table1));
	image1=create_pixmap(windowAccueil,"./accueil.jpg");
	image1=gtk_image_new_from_file("./accueil.jpg");
	gtk_table_attach_defaults(GTK_TABLE(table1),image1,0,0,0,0);

	table2=gtk_table_new(0,0,TRUE);
	gtk_container_add(GTK_CONTAINER(windowAccueil),GTK_WIDGET(table2));
	image2=create_pixmap(windowAccueil,"./accueil1.jpg");
	image2=gtk_image_new_from_file("./accueil1.jpg");
	gtk_table_attach_defaults(GTK_TABLE(table2),image2,0,0,0,0);

	table3=gtk_table_new(0,0,TRUE);
	gtk_container_add(GTK_CONTAINER(windowAccueil),GTK_WIDGET(table3));
	image3=create_pixmap(windowAccueil,"./accueil2.jpg");
	image3=gtk_image_new_from_file("./accueil2.jpg");
	gtk_table_attach_defaults(GTK_TABLE(table3),image3,0,0,0,0);



  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowAccueil = create_windowAccueil ();
  gtk_widget_show_all (windowAccueil);

  gtk_main ();
  return 0;
}

